server.port=8761

spring.application.name=service-registry

# Do not register itself as a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Disable self-preservation
eureka.server.enable-self-preservation=false

# Actuator
management.endpoints.web.exposure.include=health,info

# Logging
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO