# Application
spring.application.name=service-catalog
server.port=8082

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/service_catalog_db
spring.data.mongodb.auto-index-creation=true

# JWT - MUST MATCH AUTH SERVICE SECRET
jwt.secret=${JWT_SECRET:Wl+R5gPJafDjV/ywH4JNcnoajisNmmBnEu7ItuCQdYmLW6w8y94+XOs8FDhXfjA2fFBfYejp9EkvhxMRb8DeDA==}

# Logging
logging.level.root=INFO
logging.level.com.app.service_catalog=DEBUG
logging.level.org.springframework.security=DEBUG

# Actuator
management.endpoints.web.exposure.include=health,info