server.port=8083
spring.application.name=service-request-service

spring.data.mongodb.uri=mongodb://localhost:27017/service_request_db

# SAME SECRET AS AUTH SERVICE
jwt.secret=${JWT_SECRET:Wl+R5gPJafDjV/ywH4JNcnoajisNmmBnEu7ItuCQdYmLW6w8y94+XOs8FDhXfjA2fFBfYejp9EkvhxMRb8DeDA==}
